# Generated by Django 3.2.4 on 2021-06-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentario',
        ),
    ]
