# Generated by Django 3.2.4 on 2021-06-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_remove_avaliacao_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
