# Generated by Django 3.2.4 on 2021-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails'),
        ),
    ]
